sachaos/viddy

- args.go
- generator.go
- main.go
- snapshot.go
- viddy.go
Ref: #2
Add the following two options.
* `--shell`
* `--shell-options`
> Support options to set shell and the additoinal shell options

- .github/workflows/lint.yml
- .github/workflows/test.yml
- .gitignore
- .golang-ci.yml
- Makefile
- args.go
- args_test.go
- generator.go
- main.go
- snapshot.go
- viddy.go
sorry, had struggles rebasing commits & squashing them ...
- added golangci-lint and testing GH actions stage
- passing golangci-lint
- add makefile with various targets
- running gofmt, gci for formatting go files
> golangci-lint, ci stages, makefile

- README.md
This PR adds a reference to the existing AUR repo for Arch users.
> docs(Readme): add reference to ArchLinux AUR repo

- go.mod
- go.sum
- main.go
> Add version checker

- README.md
- viddy.go
Fix https://github.com/sachaos/viddy/issues/3
> Add help view

- go.mod
- go.sum
- viddy.go
Fix https://github.com/sachaos/viddy/issues/15
Use upstream when the PR was merged.
https://github.com/rivo/tview/pull/641
> Use forked tview temporary

- viddy.go
- Fix warning
- Modify wrong keybinding
> Fix some bugs

- README.md
I made asdf-vm plugin for viddy.
If you like it, merge please.
FYR:
* viddy plugin for asdf-vm: https://github.com/ryodocx/asdf-viddy
* asdf-vm: https://asdf-vm.com
> add asdf-vm install

- config.go
- main.go
- viddy.go
Ref https://github.com/sachaos/viddy/issues/8#issuecomment-922481834
> Add unfold option

- README.md
- config.go
- config_test.go
- main.go
- viddy.go
Add ring terminal bell changes between updates. For me it's useful additional option, especially when you are waiting for certain changes on hidden terminal window.
> add ring terminal bell changes between updates

- README.md
A Clockwork Orange was a book before it was turned into a movie. Additionally, I included a small grammar fix.
> Small adjustment to A Clockwork Orange description in README

- .github/workflows/lint.yml
- .golang-ci.yml
- Update golangci-lint version
- Disable linters
> Update golangci-lint version

- .github/workflows/release.yml
- .github/workflows/test.yml
> Update actions to use go 1.18

- viddy.go
> Quit viddy

- viddy.go
* added hotkey functionality for unfold
* added key-bindings description for unfold
Solution for #53
> feat: toggle unfold with hotkey

- viddy.go
Move to now when timemachine enabled
> Fix bug of switching time machine

- generator.go
- viddy.go
Fix https://github.com/sachaos/viddy/issues/100
> Do not execute command when suspended

- README.md
- config.go
- snapshot.go
- viddy.go
Fix https://github.com/sachaos/viddy/issues/92
> Add --no-shell option

- README.md
Please double-check for correctness.
> README: Document the option for skipping empty diffs

- src/cli.rs
> Fix shell option message for Windows

- .config/config.json5
- Cargo.lock
- Cargo.toml
- src/app.rs
- src/cli.rs
- src/components/execution_result.rs
- src/components/home.rs
- src/components/interval.rs
- src/components/status.rs
- src/config.rs
- src/main.rs
- src/runner.rs
- src/store.rs
- src/store/memory.rs
- src/store/sqlite.rs
- src/types.rs
Ref: https://github.com/sachaos/viddy/issues/38
Ref: https://github.com/sachaos/viddy/issues/52
Ref: https://github.com/sachaos/viddy/issues/104
Now, viddy save backup automatically in temporary dir.
And you can load the save file by `--lookback` or `--load` option.
> Implement save & lookback feature

- src/app.rs
- src/bytes.rs
- src/main.rs
- src/runner.rs
- src/termtext.rs
Fix tab bug
https://github.com/sachaos/viddy/issues/117#issuecomment-2294925153
> Support tab

- src/termtext.rs
Handle reset code
Ref: https://github.com/sachaos/viddy/issues/117#issuecomment-2294925153
> Handle reset code

- src/app.rs
- src/bytes.rs
I changed to handle ansi code and char width.
https://github.com/sachaos/viddy/pull/128#issuecomment-2295313756
> Support ansicode and char width for tab

- .github/workflows/cd.yml
Ref: https://github.com/sachaos/viddy/issues/117#issuecomment-2295662727
Build musl binaries
> Build musl binaries

- Cargo.lock
- Cargo.toml
> Change version to v1.0.0

- src/components/history.rs
- src/components/home.rs
- src/store/sqlite.rs
- src/widget/history_item.rs
I used [typos](https://github.com/crate-ci/typos) to detect typos.
> fix: many typos

- src/components/history.rs
Fix the bug that occurs when the action to go to latest.
> Fix go to latest bug

- Cargo.lock
- Cargo.toml
- README.md
- fix version to match with the 1.1.3 release
relates to https://github.com/Homebrew/homebrew-core/pull/192184
> chore: fix version to match with the release

- Cargo.lock
- Cargo.toml
- README.md
- src/app.rs
- src/cli.rs
- src/config.rs
- src/old_config.rs
- src/termtext.rs
Fix https://github.com/sachaos/viddy/issues/153
> Add option to disable mouse capture
